application: nasa-meteorite
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /static
  static_dir: static
  
- url: /.*
  script: main.app

libraries:
- name: jinja2
  version: 2.6
- name: ssl
  version: latest